# Generated by Django 5.2.6 on 2026-02-10 04:56

import django.template.defaulttags
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_teammember_position_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='published_date',
            field=models.DateTimeField(default=django.template.defaulttags.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='published_date',
            field=models.DateTimeField(default=django.template.defaulttags.now),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='published_date',
            field=models.DateTimeField(default=django.template.defaulttags.now),
        ),
    ]
