# Generated by Django 5.2.6 on 2026-02-10 14:48

from django.db import models

try:
    from django_ckeditor_5.fields import CKEditor5Field
except ImportError:  # pragma: no cover
    CKEditor5Field = models.TextField
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0006_alter_blogpost_published_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('summary', models.TextField()),
                ('content', CKEditor5Field(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('author_name', models.CharField(blank=True, max_length=100)),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='author_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='content',
            field=CKEditor5Field(blank=True),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='author_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='content',
            field=CKEditor5Field(blank=True),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='roadmap_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='landing_page.tag'),
        ),
    ]
