# Generated by Django 5.2.6 on 2026-02-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0007_event_blogpost_author_name_project_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio about the team member'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='skills',
            field=models.TextField(blank=True, help_text="Comma-separated skills (e.g., 'Python, Django, React')"),
        ),
        migrations.AddField(
            model_name='teammember',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
