# Generated by Django 5.2.6 on 2026-02-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0008_teammember_bio_teammember_github_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmap',
            name='image',
        ),
    ]
