# Generated by Django 5.2.6 on 2026-02-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_page", "0009_remove_roadmap_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="image",
        ),
        migrations.RemoveField(
            model_name="event",
            name="image",
        ),
        migrations.RemoveField(
            model_name="project",
            name="image",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="photo",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="URL to externally hosted image (e.g., Imgur)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="URL to externally hosted image (e.g., Imgur)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(blank=True, to="landing_page.tag"),
        ),
        migrations.AddField(
            model_name="project",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="URL to externally hosted image (e.g., Imgur)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="roadmap",
            name="tags",
            field=models.ManyToManyField(blank=True, to="landing_page.tag"),
        ),
        migrations.AddField(
            model_name="tag",
            name="color",
            field=models.CharField(default="#7da6ff", max_length=7),
        ),
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=models.SlugField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="photo_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL to externally hosted photo (e.g., Imgur)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="tags",
            field=models.ManyToManyField(blank=True, to="landing_page.tag"),
        ),
    ]
