# Generated by Django 5.2.6 on 2026-02-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_page", "0010_remove_blogpost_image_remove_event_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "profile_image",
                    models.URLField(
                        help_text="URL to externally hosted speaker photo",
                        max_length=500,
                    ),
                ),
                ("bio", models.TextField()),
                ("social_link", models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="gallery_images",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="event",
            name="location_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="event",
            name="meeting_link",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="event",
            name="mode",
            field=models.CharField(
                choices=[
                    ("physical", "Physical"),
                    ("virtual", "Virtual"),
                    ("hybrid", "Hybrid"),
                ],
                default="physical",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="requires_registration",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="tech_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="event",
            name="speakers",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="landing_page.speaker"
            ),
        ),
    ]
