# Generated by Django 5.2.6 on 2026-02-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "landing_page",
            "0011_speaker_event_gallery_images_event_location_address_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="resources",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
