# Generated by Django 5.2.6 on 2026-02-13 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_page", "0012_event_resources"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="gallery_images",
        ),
        migrations.RemoveField(
            model_name="event",
            name="resources",
        ),
        migrations.RemoveField(
            model_name="event",
            name="tech_tags",
        ),
        migrations.CreateModel(
            name="EventGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(max_length=500)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_image_items",
                        to="landing_page.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("url", models.URLField(max_length=500)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_items",
                        to="landing_page.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventTechTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tech_tag_items",
                        to="landing_page.event",
                    ),
                ),
            ],
        ),
    ]
