# Generated by Django 5.2.6 on 2026-02-14

from django.db import migrations, models

try:
    from django_ckeditor_5.fields import CKEditor5Field
except ImportError:  # pragma: no cover
    CKEditor5Field = models.TextField


def reset_rich_text_content(apps, schema_editor):
    Project = apps.get_model('landing_page', 'Project')
    BlogPost = apps.get_model('landing_page', 'BlogPost')
    Roadmap = apps.get_model('landing_page', 'Roadmap')
    Event = apps.get_model('landing_page', 'Event')

    Project.objects.update(content='')
    BlogPost.objects.update(content='')
    Roadmap.objects.update(content='')
    Event.objects.update(content='')


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0013_remove_event_gallery_images_remove_event_resources_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content',
            field=CKEditor5Field('Text', blank=True, config_name='default'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=CKEditor5Field('Text', blank=True, config_name='default'),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='content',
            field=CKEditor5Field('Text', blank=True, config_name='default'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=CKEditor5Field('Text', blank=True, config_name='default'),
        ),
        migrations.RunPython(reset_rich_text_content, migrations.RunPython.noop),
    ]
