# Generated by Django 5.2.6 on 2026-03-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_page", "0014_ckeditor5_default_and_reset_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="registration_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
