# Generated by Django 5.2.6 on 2026-03-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_page", "0015_event_registration_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, max_length=170, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="roadmap",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
