# Generated by Django 5.2.6 on 2026-03-02 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0017_backfill_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='is_open_source',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='repo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('idea', 'Idea'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='idea', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role_type', models.CharField(blank=True, max_length=120)),
                ('role_title', models.CharField(blank=True, max_length=150)),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('github_url', models.URLField(blank=True, max_length=500)),
                ('linkedin_url', models.URLField(blank=True, max_length=500)),
                ('website_url', models.URLField(blank=True, max_length=500)),
                ('bio', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='landing_page.project')),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProjectPublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('normalized_name', models.CharField(default='', editable=False, max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=160, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishers', to='landing_page.project')),
            ],
            options={
                'ordering': ('normalized_name', 'name'),
                'unique_together': {('project', 'slug')},
            },
        ),
    ]
