# Generated by Django 5.2.6 on 2026-03-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0018_project_demo_url_project_is_open_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcontributor',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='projectcontributor',
            name='role_title',
        ),
        migrations.DeleteModel(
            name='ProjectPublisher',
        ),
    ]
