"""
Django settings for backend_core project.
Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import os
from corsheaders.defaults import default_headers

# Build paths
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY
SECRET_KEY = 'django-insecure-g-a7up(22^5!lggdpuw#)pd9o6*xjvg2$p69578ht^dgx$uiv$'
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'landing_page.apps.LandingPageConfig',

    'rest_framework',
    'corsheaders',
]

try:
    import django_ckeditor_5  # noqa: F401
    INSTALLED_APPS.append('django_ckeditor_5')
except ImportError:
    pass

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend_core.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ---------------- CORS CONFIGURATION (FIXED) ----------------

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_HEADERS = list(default_headers) + [
    "ngrok-skip-browser-warning",
]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "https://barbless-martine-unartificial.ngrok-free.dev"
]

# ------------------------------------------------------------


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files
STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files are now hosted externally (e.g., Imgur) to save server storage
# No local MEDIA_ROOT configuration needed


# Custom site info
SITE_NAME = "Google Developer's Group, NEHU"


CKEDITOR_5_CONFIGS = {
    'extends': {
        'toolbar': {
            'items': [
                'heading', '|',
                'bold', 'italic', 'underline', 'link', '|',
                'alignment', '|',
                'bulletedList', 'numberedList', 'blockQuote', '|',
                'codeBlock', '|',
                'insertImage', 'mediaEmbed', '|',
                'undo', 'redo',
            ],
            'shouldNotGroupWhenFull': True,
        },
        'image': {
            'toolbar': [
                'imageTextAlternative', '|',
                'imageStyle:inline', 'imageStyle:block', 'imageStyle:side', '|',
                'resizeImage', '|',
                'imageStyle:alignLeft', 'imageStyle:alignCenter', 'imageStyle:alignRight',
            ],
            'styles': [
                'inline', 'block', 'side',
                'alignLeft', 'alignCenter', 'alignRight',
            ],
            'resizeUnit': '%',
            'resizeOptions': [
                {'name': 'resizeImage:original', 'value': None, 'label': 'Original'},
                {'name': 'resizeImage:50', 'value': '50', 'label': '50%'},
                {'name': 'resizeImage:75', 'value': '75', 'label': '75%'},
            ],
        },
        'mediaEmbed': {
            'previewsInData': True,
        },
        'codeBlock': {
            'languages': [
                {'language': 'plaintext', 'label': 'Plain text'},
                {'language': 'python', 'label': 'Python'},
                {'language': 'javascript', 'label': 'JavaScript'},
                {'language': 'bash', 'label': 'Bash'},
            ]
        },
    }
}

CKEDITOR_5_UPLOAD_PATH = 'uploads/'
CKEDITOR_5_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# Django REST Framework – force JSON responses only
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ]
}


REDIS_URL = os.getenv('REDIS_URL', '').strip()
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'club-site-backend-cache',
        }
    }
